name: Daily dbt deployment

on:
  schedule:
    - cron: '0 6 * * *' # Daily at 1AM ET / 6AM UTC
  workflow_dispatch:

jobs:
  dbt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install "dbt-duckdb"
      
      - name: Run dbt
        working-directory: dbt_bikeshare
        run: dbt run --profiles-dir .
        env:
          motherduck_token: ${{ secrets.MOTHERDUCK_TOKEN }}